### ISSUE TITLE
The rendered map is empty

### ISSUE THREAD

**Issue by dgellow** [fixme-lausanne/hackerspaces_ch#14]
That's what I see at http://hackerspaces.ch/

![screenshot](http://i.imgur.com/yHhj7zs.png)

**Comment by gcmalloc** [comment]
fixed the list was empty

**Comment by gcmalloc** [comment]
![2016-04-21-115557_1349x557_scrot](https://cloud.githubusercontent.com/assets/184983/14705067/1b47556e-07b8-11e6-9a31-1259a5fb6d52.png)
